spring.application.name=demo


# Configuración de Conexión Oracle Cloud
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# La URL indica el alias (saki_high) y la ruta donde descomprimiste el Wallet
spring.datasource.url=jdbc:oracle:thin:@bdpensamiento_high?TNS_ADMIN=C:/Users/joset/Downloads/demo/demo/src/main/resources/Wallet_BdPensamiento
# Credenciales de tu usuario de la BD
spring.datasource.username=SAKI
spring.datasource.password=32427501St_@

# Configuración de JPA / Hibernate para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# Configuración de AWS S3
aws.access.key.id=${AWS_ACCESS_KEY_ID:TU_KEY_AQUI}
aws.secret.access.key=${AWS_SECRET_ACCESS_KEY:TU_SECRET_AQUI}
aws.region=us-east-2
aws.s3.bucket.name=vivero-pensamiento-app

# Configuración de Servidor de Correo (Ejemplo con Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-correo-vivero@gmail.com
spring.mail.password=tu_contraseña_de_aplicacion_gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=trues